#! /usr/bin/env python3

import h_parser

import sys
sys.path.insert(0,"../..")

if sys.version_info[0] >= 3:
    raw_input = input

while 1:
    try:
        s = raw_input('enjoy! > ')
    except EOFError:
        break
    if not s: continue
    h_parser.parser.parse(s)
